title: "Power FX Gallery"
email: "info@creativityspark.es"
description: >- # this means to ignore newlines until "baseurl:"
  Site containing PowerFX snippets ready to use in your Power Platform developments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pfx.gallery"
logo: 'assets/images/logo.png'
twitter_username: crisfervil
github_username:  crisfervil

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 18
paginate_path: "/page/:num/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
